### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by neizod** [narze/resume#3]
After `npm install` and editing file `src/data.ts`, try running it with `npm run dev` yield this result:

```
> sttv@0.0.0 dev
> NODE_ENV=development vite

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/neizod/git/test-resume/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:23:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by narze** [comment]
That's weird...
Which node.js version did you use?

**Comment by neizod** [comment]
```
$ node -v
v10.19.0
```

**Comment by narze** [comment]
Maybe you need later version of nodejs (>= v12) 
I tried to install nodejs v10 but it cannot be installed on M1 machines :(

**Comment by neizod** [comment]
Oh, I see. Newer node version solve it perfectly!
